config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end

  devise_for :admins
  devise_for :users
  
  get 'inicio', to: 'site/welcome#index'
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verifyPassword, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.all.page(params[:page])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Admin criado com sucesso"
    else
      render :new
    end
  end

  def edit
    @admin = Admin.find(params[:id])
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Admin atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
     if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Admin excluído com sucesso"
    else
      render :index
    end
  end

  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end  

  def verifyPassword
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :get_subjects, only: [:new, :edit]
  before_action :set_question, only: [:edit, :update, :destroy]

  def index
    @questions = Question.includes(:subject).order(:subject).page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

  private

  def params_question
    params.require(:question).permit(:description, :subject_id, answers_attributes: [:id, :description, :correct, :_destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.all.order(:description).page(params[:page])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: "Assunto criado com sucesso"
    else
      render :new
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
     if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto excluído com sucesso"
    else
      render :index
    end
  end

  private

  def params_subject
    params.require(:subject).permit(:description)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end  
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    layout "admins_backoffice"
    before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :layout_by_resource

    private

    def layout_by_resource
        if devise_controller?
            "#{resource_class.to_s.downcase}_devise"
        else
            "application"
        end
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < 
SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
    def index
    end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    layout "users_backoffice"
    before_action :authenticate_user!
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper

    def translate_attribute(object = nil, attribute = nil)
        if attribute && object
            object.model.human_attribute_name(attribute)
        else
            "Informe os parâmetros corretamente"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/admins/edit.html.erb
<%= render partial: 'admins_backoffice/admins/shared/form', locals: { action_message: 'Editando administrador'} %>

app/views/admins_backoffice/admins/index.html.erb
<h1>Listando administradores</h1>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th><%= translate_attribute(@admins, :email) %></th>
                <th>
                    <%= link_to new_admins_backoffice_admin_path, class:"btn btn-success btn-circle" do %>
                        <i class="fa fa-plus"></i>
                    <% end %>
                </th>
            </tr>
        </thead>
        <tbody>
            <% @admins.each do |admin| %>
                <tr>
                    <td><%= admin.id %></td>
                    <td><%= admin.email %></td>
                    <td style="width: 100px;">
                        <%= link_to edit_admins_backoffice_admin_path(admin), class:"btn btn-primary btn-circle" do %>
                            <i class="fa fa-edit"></i>
                        <% end %>
                        
                        <%= link_to admins_backoffice_admin_path(admin), method: :delete, data: { confirm: 'Tem certeza?' }, class:"btn btn-danger btn-circle" do %>
                            <i class="fa fa-trash"></i>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div class="text-center">
        <%= paginate @admins %>
    </div>
</div>

app/views/admins_backoffice/admins/new.html.erb
<%= render partial: 'admins_backoffice/admins/shared/form', locals: { action_message: 'Criando administrador'} %>

app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested-fields">
    <%= f.label :description %> </br>
    <%= f.text_field :description %>
    <%= f.check_box :correct %> Correta?
    <%= link_to_remove_association 'Remover', f %>
</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form', locals: { action_message: 'Editando assunto'} %>

app/views/admins_backoffice/questions/index.html.erb
<h1>Listando perguntas</h1>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th><%= translate_attribute(@questions, :subject) %></th>
                <th><%= translate_attribute(@questions, :description) %></th>
                <th>
                    <%= link_to new_admins_backoffice_question_path, class:"btn btn-success btn-circle" do %>
                        <i class="fa fa-plus"></i>
                    <% end %>
                </th>
            </tr>
        </thead>
        <tbody>
            <% @questions.each do |question| %>
                <tr>
                    <td><%= question.id %></td>
                    <td><%= question.subject.description.truncate(30) %></td>
                    <td><%= question.description.truncate(50) %></td>
                    <td style="width: 100px;">
                        <%= link_to edit_admins_backoffice_question_path(question), class:"btn btn-primary btn-circle" do %>
                            <i class="fa fa-edit"></i>
                        <% end %>
                        
                        <%= link_to admins_backoffice_question_path(question), method: :delete, data: { confirm: 'Tem certeza?' }, class:"btn btn-danger btn-circle" do %>
                            <i class="fa fa-trash"></i>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div class="text-center">
        <%= paginate @questions %>
    </div>
</div>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form', locals: { action_message: 'Criando assunto'} %>

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', locals: { action_message: 'Editando assunto/area'} %>

app/views/admins_backoffice/subjects/index.html.erb
<h1>Listando Assuntos/Areas</h1>
<div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th><th><%= translate_attribute(@subjects, :description) %></th></th>
                <th>
                    <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle" do %>
                        <i class="fa fa-plus"></i>
                    <% end %>
                </th>
            </tr>
        </thead>
        <tbody>
            <% @subjects.each do |subject| %>
                <tr>
                    <td><%= subject.id %></td>
                    <td><%= subject.description %></td>
                    <td style="width: 100px;">
                        <%= link_to edit_admins_backoffice_subject_path(subject), class:"btn btn-primary btn-circle" do %>
                            <i class="fa fa-edit"></i>
                        <% end %>
                        
                        <%= link_to admins_backoffice_subject_path(subject), method: :delete, data: { confirm: 'Tem certeza?' }, class:"btn btn-danger btn-circle" do %>
                            <i class="fa fa-trash"></i>
                        <% end %>
                        
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div class="text-center">
        <%= paginate @subjects %>
    </div>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', locals: { action_message: 'Criando assunto/area'} %>

app/views/admins_backoffice/welcome/index.html.erb
<h1>AdminsBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>

<%= link_to "Fazer logoff", destroy_admin_session_path, method: :delete %>

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>

<% if user_signed_in? %>
  <p>Usuário ESTÁ logado / <%= current_user.email %> </p>
<% else %>
  <p>Usuário NÃO está logado</p>
<% end %>

<% if admin_signed_in? %>
  <p>Administrador ESTÁ logado / <%= current_admin.email %> </p>
<% else %>
  <p>Administrador NÃO está logado</p>
<% end %>